### ISSUE TITLE
[\s\S] doesn't seem to work

### ISSUE THREAD

**Issue by Twigpig** [andgineer/TRegExpr#4]
Using Regex "Test:\s*([\s\S]*?)\s*;" (without quotes, obviously) with an input of "Test: hello ;" correctly Returns "hello" on other Regex tools (e.g. http://www.regexr.com/) but returns no results using TRegExpr.

![image](https://user-images.githubusercontent.com/6820382/27226737-558395cc-5298-11e7-9fcb-1b28e4a33339.png)

Using "Test:\s*(.*?)\s*;" works for this case in TRegExpr but obviously wouldn't do the same job if you were using a multi-line input string.

![image](https://user-images.githubusercontent.com/6820382/27226763-6d766b78-5298-11e7-9394-87702e800fbf.png)

vs

![image](https://user-images.githubusercontent.com/6820382/27226829-b4c80aa4-5298-11e7-9397-2c65097b5853.png)

Unless I'm mistaken, the below should return "hell\nlo":

![image](https://user-images.githubusercontent.com/6820382/27226867-dc89ff52-5298-11e7-94ae-5c98e2137f7e.png)

**Comment by masterandrey** [comment]
It looks the same issue as https://bugs.freepascal.org/view.php?id=34130

In this implementation of regexpr you cannot use 'not-space' inside character class.
The compiler expects just simple chars or intervals (like [a-z]).

You can invert character class as [^a-z] but I do not understand what do you want to do.

for example expression '(?m)Test:\s*(.*?)\s;' will be found in input text 'Test: hel'#$d#$a'lo ;' and returns 'Test: hel'#$d#$a'lo ;'
https://github.com/masterandrey/TRegExpr/commit/3bf2b3664a510b93e1e224907bb9c7c7dff50858

**Comment by Twigpig** [comment]
The problem with using "(.*?)" instead of "([\s\S]*?)" is that it doesn't return results that include line breaks, even with the multiline flag enabled (as demonstrated in my second to last screenshot above).

**Comment by masterandrey** [comment]
(.) actually works - I even add the test for it ((?m) switches on multiline flag):https://github.com/masterandrey/TRegExpr/commit/3bf2b3664a510b93e1e224907bb9c7c7dff50858 But of cause you need '*' because there are more than one char in you example. Please help me to reproduce the problem and I will fix it.The best way - give me or send in github pull request a test that will fail but you think it should not. [\s\S] just won't work because TRegExpr does not work with metachars inside char class (square brackets '[]').TRegExpr expects inside char class just chars or intervals (like [a-z]).  22.10.2018, 16:09, "Twigpig" <notifications@github.com>:The problem with using "(.?)" instead of "([\s\S]?)" is that it doesn't return results that include line breaks, even with the multiline flag enabled (as demonstrated in my second to last screenshot above).—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Twigpig** [comment]
> [\s\S] just won't work because TRegExpr does not work with metachars inside char class (square brackets '[]').TRegExpr expects inside char class just chars or intervals (like [a-z]).

I was classing this as a bug because I wrongly expected this kind of syntax to be consistent across all variations of RegEx and other implementations of RegEx allow it. However it sounds like you're suggesting it's intentionally not supported in TRegExpr. If you don't mind me asking, is there a reason? Was it by design?

My aim was to produce a variation of the above RegEx that could be used in both TRegExpr and http://www.regexr.com/ but it seems that the required syntax for each is incompatible with the other (and I suppose that's okay).

Thank you for taking the time to look into this and getting back to me. Much appreciated.

**Comment by masterandrey** [comment]
This library I wrote 20 years ago and at the time I implemented just the re subset that I need.
You know, at the moment there was no other libraries for regular expressions in Delphi.
So I implemented it myself but just for my tasks.

Now I do not use pascal in my everyday life so if we are going to continue development we need somebody with current pascal skills and wish to join TRegExpr development.

In fact that's the main reason why I published it on github.

**Comment by Twigpig** [comment]
Ah, I see. So it's just something it doesn't currently handle, rather than something it shouldn't allow on principle? If that's the case, perhaps I'll implement the feature myself if I can find the time.

Thanks again.

**Comment by masterandrey** [comment]
As I see there no such thing in POSIX basic standard
https://en.wikipedia.org/wiki/Regular_expression#POSIX_basic_and_extended

As for extensions this is [:blank:] in POSIX, \s in vim and no such thing in perl.

Or this is [:digit:] for POSIX and \w for vim and perl.

May be perl way is better because POSIX is too verbose.
But with perl you have to understand that for example \r means one character and \w means character class.
Do not see any problems with that..

**Comment by totyaxy** [comment]
> This library I wrote 20 years ago 

It's very intresting, because the latest trunk version works correctly with UTF8 chars in Lazarus 2.0.3 / fpc 3.0.5. , and no need anymore the complicate UTF8<->unicodestring conversion.

Thank you for this library!

**Comment by Alexey-T** [comment]
@andgineer Are you sure that char classes dont work in `[ ]`? CudaText can find by regex:

[\w\-] - wordchars and -
[\dx] - digits and x

**Comment by Alexey-T** [comment]
\S \D \W not allowed in `[]`, they are handled here
```
                case regparse^ of // r.e.extensions
                  'd': EmitRangeStr ('0123456789');
                  'w': EmitRangeStr (WordChars);
                  's': EmitRangeStr (SpaceChars);
                  else EmitSimpleRangeC (UnQuoteChar (regparse));
                 end; { of case}
```
we cannot add here handling of \D\ W\ S - too much chars needed in param (65k).
